Pamtim/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Net;
using System.Security.Claims;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Pamtim.Models;

namespace Pamtim.Controllers
{
    public class ScheduleController : Controller
    {



        [Authorize]
        public ActionResult Pregled()
        {

            var User_ID = Request.Cookies["User_ID"].Values;



            DataTable dt3 = new DataTable();
            using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["pamtim"].ConnectionString))
            {
                conn.Open();
                if (conn.State == ConnectionState.Open)
                {

                    var upit = "select Semester.ID_Semester from Semester INNER JOIN [User] ON Semester.User_ID = [User].ID_User " +
                               "where [User].ID_User = " + User_ID;
                    using (var cmd = new SqlCommand(upit, conn))
                    {
                        cmd.CommandType = CommandType.Text;
                        var sqlda = new SqlDataAdapter(cmd);
                        sqlda.Fill(dt3);
                    }
                }
            }
            ViewBag.podaci = dt3;

            int SemesterID = 0;
            foreach (DataRow r in dt3.Rows)
            {
                SemesterID = (int)r["ID_Semester"];
            }


            DataTable dt = new DataTable();
            using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["pamtim"].ConnectionString))
            {
                conn.Open();
                if (conn.State == ConnectionState.Open)
                {

                    var upit = "select Event.*, Activity.Name as Activity, Course.Name AS Course, [User].ID_User, Activity.AllowedAbsence from " +
                               "Event INNER JOIN Activity ON Event.Activity_ID = Activity.ID_Activity INNER JOIN " +
                               "Course ON Activity.Course_ID = Course.ID_Course INNER JOIN " +
                               "Semester ON Course.Semester_ID = Semester.ID_Semester INNER JOIN " +
                               "[User] ON Semester.User_ID = [User].ID_User " +
                               "where [User].ID_User = " + User_ID + "AND Semester.ID_Semester = " + SemesterID + "order by Event.Start";
                    using (var cmd = new SqlCommand(upit, conn))
                    {
                        cmd.CommandType = CommandType.Text;
                        var sqlda = new SqlDataAdapter(cmd);
                        sqlda.Fill(dt);
                    }
                }
            }


            ViewBag.podaci = dt;

            var Schedules = new ListofScheduleViewModel();

            Schedules.Items = new List<ScheduleViewModel>();

            foreach (DataRow r in dt.Rows)
            {


                DataTable dt2 = new DataTable();
                using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["pamtim"].ConnectionString))
                {
                    conn.Open();
                    if (conn.State == ConnectionState.Open)
                    {

                        var upit = "select COUNT(Activity_ID) as broj from Absence where Activity_ID = '" + r["Activity_ID"] + "'";
                        using (var cmd = new SqlCommand(upit, conn))
                        {
                            cmd.CommandType = CommandType.Text;
                            var sqlda = new SqlDataAdapter(cmd);
                            sqlda.Fill(dt2);
                        }
                    }
                }


                var Schedule = new ScheduleViewModel();
                Schedule.ID_Event = r["ID_Event"].ToString();
                Schedule.Activity_ID = r["Activity_ID"].ToString();
                Schedule.Day = r["Day"].ToString();
                Schedule.Start = (TimeSpan)r["Start"];
                Schedule.Finish = (TimeSpan)r["Finish"];
                Schedule.CourseName = r["Course"].ToString();
                Schedule.ActivityName = r["Activity"].ToString();
                Schedule.AllowedAbsence = (int)r["AllowedAbsence"];
                Schedule.CountAbsence = dt2.Rows[0].Field<int>("broj");
                Schedule.Location = r["Location"].ToString();

                Schedules.Items.Add(Schedule);
            }

            

            return View(Schedules);
        }


        

    }
}

Pamtim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="hr">
<head>
    <link rel="manifest" href="~/manifest.json" />

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#0dbaff" />
    <title>@ViewBag.Title - Pamtim</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="icon" href="../../Content/icons/icon-192x192.png" />
    <link rel="aple-touch-icon" href="../../Content/icons/ios-icon-192x192.png" />
    <meta name="Description" content="Author: Filip Tezak, App: Pamtim.com">
    <meta /> 
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-148219487-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-148219487-1');
    </script>

</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-theme">
        @Html.ActionLink("Pamtim", "Pregled", "Semestri", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">@Html.ActionLink("Raspored", "Pregled", "Schedule", new { area = "" }, new { @class = "nav-link" })</li>
            </ul>
            <ul class="navbar-nav ml-auto">
                @Html.Partial("_LoginPartial")
            </ul>
        </div>

    </nav>


    <div class="container body-content">
        @RenderBody()
        

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


<script>
    
    if ('serviceWorker' in navigator) {
        window.addEventListener('load', function() {
            navigator.serviceWorker.register('../../serviceworker.js').then(function() {
                console.log('Service Worker Registered');
            });
        });
    }

    
    if ('serviceWorker' in navigator) {
        window.addEventListener('load', function() {
            console.log('[Semestri] Pregled semestara je učitan!');
            event.waitUntil(
                caches.open('Offline')
                .then(function(cache) {
                    console.log('[Service Worker] Precaching...');
                    cache.add('https://www.pamtim.com/Offline/Offline');    
                })
            )
        });
    }

</script>
     

</body>
</html>